/* ==========================================================================
   STITBD — Data Layer (vanilla JS port of companyData.ts)
   ========================================================================== */

const COMPANY_INFO = {
  name: 'STITBD',
  fullName: 'Software Technology Info Tech BD',
  tagline: 'Empowering Businesses with Cutting-Edge Software & IT Solutions',
  sinceYear: 2014,
  yearsOfExcellence: new Date().getFullYear() - 2014,
  email: 'info@stitbd.com',
  supportEmail: 'shaokat71@gmail.com',
  phonePrimary: '+880 1757-769498',
  phoneSecondary: '+880 11834-163689',
  whatsapp: '+880 1757-769498',
  address: 'Level 5, Software Technology Park, Kawran Bazar, Dhaka-1215, Bangladesh',
  officeHours: '24/7 Technical Support & Customer Service',
  facebook: 'https://facebook.com/stitbd',
  linkedin: 'https://linkedin.com/company/stitbd',
  youtube: 'https://youtube.com/c/stitbd',
  github: 'https://github.com/stitbd',
};

const SERVICES = [
  {
    id: 'software-dev',
    title: 'Software Development',
    description: 'Tailor-made desktop, web, and cloud-based software engineered to streamline complex business workflows, enterprise resource management, and daily operational processes.',
    fullDescription: 'STITBD delivers custom software development services that transform how businesses operate. From enterprise resource planning (ERP) systems to customer relationship management (CRM) platforms, our team builds scalable, secure, and efficient solutions. We specialize in financial accounting software, inventory management systems, and industry-specific applications. Our development process includes requirement analysis, agile development, rigorous testing, deployment, and ongoing maintenance. With over 12 years of experience, we have successfully delivered 1,200+ projects across Bangladesh and international markets.',
    iconName: 'bi-code-slash',
    badge: 'Core Specialty',
    features: [
      'Custom ERP & CRM Architectures',
      'High-Performance Cloud & Local Databases',
      'Automated Billing & Financial Ledger Accounting',
      'Multi-User Role & Access Rights Management',
    ],
  },
  {
    id: 'web-dev',
    title: 'Website Design & Development',
    description: 'Ultra-fast, responsive corporate portals, custom Web APIs, and high-conversion E-commerce platforms built with modern frontend frameworks and secure backends.',
    fullDescription: 'Our web development team creates stunning, high-performance websites that drive business growth. We build corporate portals, e-commerce platforms, custom web applications, and API-driven solutions. Using modern frameworks like React.js, Next.js, and Laravel, we ensure your website is fast, secure, and mobile-responsive. We integrate local payment gateways (bKash, Nagad), implement SEO best practices, and deliver user-centric designs that convert visitors into customers. Every website we build includes SSL security, regular backups, and 24/7 monitoring.',
    iconName: 'bi-window-stack',
    badge: 'Popular',
    features: [
      'React.js, Next.js & Laravel High-Speed Stack',
      'Mobile-First Responsive Layouts & Sleek UI/UX',
      'Local & Global Payment Gateway Integrations',
      'SEO-Optimized & Speed Audited Codebase',
    ],
  },
  {
    id: 'domain-hosting',
    title: 'Domain Registration & Hosting',
    description: 'High-speed BTTB .bd & global TLD domain registration paired with NVMe SSD cloud hosting, cPanel management, SSL certificates, and guaranteed 99.9% uptime.',
    fullDescription: 'STITBD is an authorized BTTB domain registrar for Bangladesh domains (.com.bd, .bd) and also offers all global TLDs (.com, .net, .org, .info, .xyz, etc.). Our cloud hosting solutions feature NVMe SSD storage, LiteSpeed web servers, free Let\'s Encrypt SSL, daily automated backups, and cPanel control panel. We guarantee 99.9% uptime with proactive DDoS protection and 24/7 server health monitoring. Our DNS management includes free email hosting, subdomain creation, and domain forwarding services.',
    iconName: 'bi-hdd-network',
    badge: 'Instant Setup',
    features: [
      'BTTB Authorized .com.bd & .bd Domain Provider',
      'High-Speed NVMe Pure SSD Cloud Servers',
      'Free Let\'s Encrypt SSL & Automated Backups',
      '24/7 Server Health Monitoring & DDoS Defense',
    ],
  },
  {
    id: 'app-dev',
    title: 'Android & iOS App Development',
    description: 'Cross-platform Flutter & native mobile applications with sleek user interfaces, offline data sync, push notifications, and real-time backend integration.',
    fullDescription: 'Our mobile app development team builds high-quality Android and iOS applications using Flutter for cross-platform efficiency and native technologies for platform-specific needs. We create apps for e-commerce, healthcare, education, logistics, and enterprise use cases. Our apps feature biometric login, push notifications, offline data synchronization, real-time chat, in-app payments, and robust backend API integration. We handle the entire lifecycle from UI/UX design to Play Store and App Store deployment, ensuring your app meets all platform guidelines and performance standards.',
    iconName: 'bi-phone',
    badge: 'iOS & Android',
    features: [
      'Flutter Cross-Platform Efficiency',
      'Real-Time Firebase & REST API Integration',
      'Biometric Login & In-App Payment Gateways',
      'Play Store & App Store Deployment Support',
    ],
  },
  {
    id: 'cctv-solutions',
    title: 'CCTV Camera Solutions',
    description: 'Complete HD IP surveillance systems, remote smartphone monitoring, biometric time-attendance hardware, and enterprise security access control setups.',
    fullDescription: 'We provide end-to-end security solutions including HD IP CCTV cameras, NVR/DVR systems, biometric time-attendance devices, and access control systems. Our team handles site surveys, camera placement optimization, cable network installation, and system configuration. All systems support remote smartphone monitoring, motion detection alerts, and cloud video storage. We integrate biometric fingerprint and face recognition attendance systems that sync with HR and payroll software. Our security solutions are designed for offices, factories, banks, educational institutions, and residential buildings.',
    iconName: 'bi-camera-video',
    badge: 'Hardware & Security',
    features: [
      'High-Definition IP & Analog Surveillance',
      'Remote Live Monitoring via Mobile App',
      'Biometric Fingerprint & Face Recognition Attendance',
      'On-Site Cable Network & NVR/DVR Installation',
    ],
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    description: 'Data-driven online growth strategies including Search Engine Optimization (SEO), Facebook & Instagram targeted advertising, Google Ads, and brand campaigns.',
    fullDescription: 'Our digital marketing team drives measurable business growth through targeted online campaigns. We offer comprehensive SEO services (on-page, off-page, technical), social media advertising (Facebook, Instagram, YouTube), Google Ads (search, display, shopping), and content marketing. We create data-driven strategies, design compelling creatives, manage ad budgets effectively, and provide detailed performance analytics. Our campaigns are optimized for lead generation, brand awareness, e-commerce sales, and customer retention. We help businesses of all sizes build a strong online presence and achieve their marketing goals.',
    iconName: 'bi-megaphone',
    badge: 'ROI Focused',
    features: [
      'Targeted Facebook, Instagram & YouTube Ad Campaigns',
      'On-Page & Off-Page Organic SEO Ranking',
      'Social Media Content Creation & Branding',
      'Conversion Rate Optimization & Lead Funnels',
    ],
  },
];

const READY_SOFTWARE_PRODUCTS = [
  {
    id: 'hr-payroll',
    name: 'HR & Payroll Management System',
    category: 'Enterprise & ERP',
    shortDescription: 'Complete employee lifecycle management with biometric attendance, salary calculation, leave tracking, and tax reports.',
    fullDescription: 'An all-in-one HR & Payroll suite designed for Bangladeshi and international organizations. Handles biometric device synchronization, complex salary structures, OT (Overtime) calculation, provident fund, tax deduction, loan management, and mobile self-service app.',
    features: ['Biometric Device Integration', 'Automated Payslip & Bank Ledger', 'Leave & Loan Approval Workflows', 'Tax & Festival Bonus Management'],
    icon: 'bi-people',
    badge: 'Best Seller',
    rating: 4.9,
    popular: true,
    targetUsers: 'Corporate offices, Garments, Factories, Banks, IT firms',
    modules: ['Employee Database', 'Biometric Attendance', 'Payroll Processing', 'Leave Portal', 'Performance Appraisal', 'Tax Engine']
  },
  {
    id: 'education-mgmt',
    name: 'Education & School Management System',
    category: 'Education & Health',
    shortDescription: 'Comprehensive school, college, and university management system with student portal, fees collection, SMS alert, and result publishing.',
    fullDescription: 'Streamline campus operations with digital student admissions, online fee collection via mobile banking (bKash/Nagad), automated report card generator, teacher schedules, hostel management, and instant SMS updates to parents.',
    features: ['Student Admission & ID Cards', 'Fees Collection & bKash Gateway', 'Exam Gradebook & Result Cards', 'Automated Parent SMS Alerts'],
    icon: 'bi-mortarboard',
    badge: 'Top Rated',
    rating: 4.9,
    popular: true,
    targetUsers: 'Schools, Colleges, Universities, Coaching Centers, Madrasas',
    modules: ['Admission System', 'Fees Ledger', 'Exam & Marksheet', 'Library Management', 'Hostel Portal', 'Transport Tracker']
  },
  {
    id: 'restaurant-pos',
    name: 'Restaurant & Cafe Management Software',
    category: 'Retail & POS',
    shortDescription: 'Touchscreen POS, Kitchen Display System (KDS), table reservation, recipe costing, and multi-branch inventory control.',
    fullDescription: 'Tailored for restaurants, fast-food outlets, and cafes. Features fast order taking, waiter mobile ordering app, kitchen order tickets (KOT), recipe ingredient deductions, VAT invoices, and sales analytics.',
    features: ['Touchscreen Billing & KOT', 'Recipe & Ingredient Deductions', 'Waiter Android Ordering App', 'Multi-Branch Sales Dashboard'],
    icon: 'bi-cup-hot',
    badge: 'Popular',
    rating: 4.8,
    popular: true,
    targetUsers: 'Restaurants, Cafes, Bakeries, Cloud Kitchens, Food Courts',
    modules: ['POS Terminal', 'Kitchen Display System', 'Inventory Control', 'Table Reservation', 'Recipe Costing', 'Customer Loyalty']
  },
  {
    id: 'enterprise-erp',
    name: 'Enterprise Resource Planning (ERP)',
    category: 'Enterprise & ERP',
    shortDescription: 'Unified business management software integrating accounting, procurement, sales, multi-warehouse inventory, and executive BI dashboards.',
    fullDescription: 'Modular ERP platform designed to eliminate data silos. Real-time insights across finance, purchase orders, sales funnels, stock balance across multiple godowns, and executive financial audit reporting.',
    features: ['Multi-Branch Godown Sync', 'Double-Entry Accounting Ledger', 'Purchase & Vendor Management', 'Real-Time Executive Analytics'],
    icon: 'bi-diagram-3',
    badge: 'Enterprise Flagship',
    rating: 5.0,
    popular: true,
    targetUsers: 'Manufacturers, Wholesale Distributors, Large Enterprises, Trading Companies',
    modules: ['General Ledger', 'Inventory Control', 'Purchase & Sales', 'Fixed Assets', 'Executive BI Dashboard', 'Audit Trail']
  },
  {
    id: 'pos-retail',
    name: 'Point of Sale (POS) & Retail Software',
    category: 'Retail & POS',
    shortDescription: 'Superfast barcode scanning POS with stock reorder alerts, customer ledger, VAT invoices, and profit/loss calculation.',
    fullDescription: 'Designed for retail shops, super shops, clothing boutiques, and electronics stores. Includes fast barcode generation, thermal receipt printing, due customer management, supplier accounts, and profit margin analysis.',
    features: ['Barcode Scan & Thermal Printing', 'Low Stock & Expiry Alerts', 'Customer Due Ledger & SMS', 'Daily Profit/Loss Analysis'],
    icon: 'bi-bag-check',
    badge: 'Essential',
    rating: 4.9,
    popular: true,
    targetUsers: 'Super Shops, Boutiques, Electronics Stores, Hardware Shops',
    modules: ['POS Terminal', 'Stock Control', 'Customer CRM', 'Supplier Ledger', 'Barcode Generator', 'VAT Accounting']
  },
  {
    id: 'courier-mgmt',
    name: 'Courier & Parcel Delivery Management',
    category: 'Services & Logistics',
    shortDescription: 'End-to-end parcel booking, rider dispatching, merchant panel, barcode tracking, and COD payment reconciliation.',
    fullDescription: 'Comprehensive courier logistics engine for nationwide delivery firms. Merchants can create orders, track live statuses, receive cash-on-delivery (COD) payouts, while riders use an Android app for barcode scanning and delivery updates.',
    features: ['Merchant Portal & API', 'Rider Smartphone App', 'Live Parcel Barcode Tracking', 'Automated COD Financial Settlement'],
    icon: 'bi-truck',
    badge: 'Hot Product',
    rating: 4.8,
    popular: true,
    targetUsers: 'E-commerce Courier Companies, Express Delivery Services, Logistics Firms',
    modules: ['Merchant Panel', 'Hub & Dispatch Operations', 'Rider App', 'COD Payment Engine', 'Customer Tracking', 'Accounts']
  },
  {
    id: 'hospital-mgmt',
    name: 'Hospital & Clinical Management System',
    category: 'Education & Health',
    shortDescription: 'OPD/IPD patient registration, doctor appointment scheduling, pathology lab tests, pharmacy billing, and bed management.',
    fullDescription: 'Streamline healthcare facilities with digital patient health records (EMR), prescription writing module, pathology lab machine integration, bed/cabin allocation, and hospital financial billing.',
    features: ['OPD & IPD Billing Engine', 'Pathology Lab Test Reports', 'Doctor Prescriptions & Schedule', 'Cabin & Bed Occupancy Grid'],
    icon: 'bi-hospital',
    badge: 'Medical Grade',
    rating: 4.9,
    popular: true,
    targetUsers: 'Hospitals, Clinics, Diagnostic Centers, Specialized Medical Institutes',
    modules: ['Patient Registration', 'Doctor Appointments', 'Pathology & Radiology', 'IPD Bed Management', 'Pharmacy Sales', 'Insurance & Billing']
  },
  {
    id: 'real-estate-mgmt',
    name: 'Real Estate & Property Management',
    category: 'Real Estate & Infrastructure',
    shortDescription: 'Plot/Apartment booking tracking, customer installment schedules, land record archive, and CRM lead conversion.',
    fullDescription: 'Customized for real estate developers and property managers. Track plot availability maps, installment payment schedules, automated SMS payment reminders, land registration records, and agent commission tracking.',
    features: ['Apartment/Plot Booking Ledger', 'Customer Installment Tracker', 'Agent Commission Calculator', 'Lead Management CRM'],
    icon: 'bi-building',
    badge: 'Industry Standard',
    rating: 4.7,
    popular: false,
    targetUsers: 'Real Estate Developers, Housing Societies, Property Management Agencies',
    modules: ['Property Registry', 'Booking & Sales', 'Installment Schedule', 'CRM Leads', 'Land Record Vault', 'Financial Accounts']
  },
  {
    id: 'microfinance-mgmt',
    name: 'Microfinance & Cooperative Software',
    category: 'Enterprise & ERP',
    shortDescription: 'Daily/Weekly microfinance loan distribution, savings collection, field collector app, and interest calculation.',
    fullDescription: 'Automates Somity (cooperative society) and microfinance institution operations. Field workers collect daily/weekly installments via mobile app with instant Bluetooth receipt printing and SMS receipt delivery.',
    features: ['Daily/Weekly Loan & Savings', 'Field Collector Mobile App', 'Automated Interest Calculation', 'Microfinance Audit Reports'],
    icon: 'bi-cash-coin',
    badge: 'Fintech',
    rating: 4.8,
    popular: false,
    targetUsers: 'Microfinance MFOs, Credit Cooperative Societies (Somity), NGOs',
    modules: ['Member Registry', 'Loan Disbursement', 'Savings Scheme', 'Field Collector App', 'Audit Reports', 'SMS Alerts']
  },
  {
    id: 'pharmacy-pos',
    name: 'Pharmacy & Medicine Shop POS',
    category: 'Retail & POS',
    shortDescription: 'Batch number expiry tracking, generic medicine lookup, shelf rack location, and doctor prescription scanner.',
    fullDescription: 'Pharmacy software with instant generic substitute lookup, drug expiry warnings, batch-wise inventory tracking, purchase ledger, and rapid billing counter.',
    features: ['Generic Medicine Search', 'Near-Expiry Item Alerts', 'Batch-Wise Inventory Control', 'Supplier Purchase Ledger'],
    icon: 'bi-capsule',
    badge: 'Rx Certified',
    rating: 4.9,
    popular: false,
    targetUsers: 'Retail Pharmacies, Hospital Drugstores, Medicine Wholesalers',
    modules: ['POS Counter', 'Generic Database', 'Batch & Expiry Tracker', 'Purchase Ledger', 'Rack Mapping', 'VAT Reporting']
  },
  {
    id: 'hotel-resort',
    name: 'Hotel & Resort Booking Management',
    category: 'Services & Logistics',
    shortDescription: 'Front desk check-in/out, online room reservation engine, housekeeping management, and room service billing.',
    fullDescription: 'Hotel management solution for front office reservations, night audit, housekeeping status grid, restaurant room charges billing, and guest feedback management.',
    features: ['Interactive Room Grid', 'Front Office Check-In/Out', 'Room Service & Laundry Billing', 'Direct Online Booking Engine'],
    icon: 'bi-houses',
    badge: 'Hospitality',
    rating: 4.8,
    popular: false,
    targetUsers: 'Hotels, Resorts, Guest Houses, Serviced Apartments',
    modules: ['Reservation Engine', 'Front Desk Grid', 'Housekeeping', 'Point of Sale (Food/Laundry)', 'Guest CRM', 'Night Audit']
  },
  {
    id: 'garments-erp',
    name: 'Garments & Textile ERP Software',
    category: 'Enterprise & ERP',
    shortDescription: 'Merchandising order costing, fabric inventory, cutting/sewing line audit, commercial export documentation.',
    fullDescription: 'Specially engineered for Bangladesh ready-made garments (RMG) factories. Track buyer orders, Consumption BOM, Master L/C & Back-to-Back L/C, production line efficiency, and packing list generation.',
    features: ['Merchandising Costing & BOM', 'Master L/C & Export Documents', 'Sewing Line Efficiency Tracker', 'Yarn & Fabric Stock Ledger'],
    icon: 'bi-scissors',
    badge: 'RMG Specialized',
    rating: 5.0,
    popular: true,
    targetUsers: 'Garment Factories, Buying Houses, Textile Mills, Apparel Exporters',
    modules: ['Merchandising', 'Commercial L/C', 'Fabric & Trims Inventory', 'Production Audit', 'Quality Control', 'Export Documentation']
  },
  {
    id: 'auto-workshop',
    name: 'Auto Workshop & Garage Management',
    category: 'Services & Logistics',
    shortDescription: 'Vehicle digital job cards, spare parts stock, mechanic commission tracking, and vehicle service reminders.',
    fullDescription: 'Manage automobile repair workshops with ease. Create vehicle inspection job cards, track spare parts consumed per vehicle, assign mechanics, send automated next-service SMS, and print customer bills.',
    features: ['Vehicle Inspection Job Cards', 'Spare Parts Inventory Control', 'Mechanic Labor & Commission', 'Next Service Date SMS Alerts'],
    icon: 'bi-tools',
    badge: 'Automotive',
    rating: 4.7,
    popular: false,
    targetUsers: 'Auto Repair Garages, Car Service Centers, Bike Dealerships',
    modules: ['Job Card System', 'Spare Parts Inventory', 'Mechanic Payroll', 'Customer Service History', 'Billing & Accounts']
  },
  {
    id: 'travel-agency',
    name: 'Travel Agency & Tour Booking ERP',
    category: 'Services & Logistics',
    shortDescription: 'Air ticket ledger, tour package customization, visa processing tracking, customer invoices, and GDS accounting.',
    fullDescription: 'Complete ERP software for travel agencies. Manage airline ticket bookings (SABRE/Amadeus sync), visa application tracking, Hajj & Umrah package management, customer passports vault, and vendor accounts.',
    features: ['Air Ticket Ledger & Refund Track', 'Visa Application Process Tracking', 'Custom Tour Package Builder', 'Hajj & Umrah Management'],
    icon: 'bi-airplane',
    badge: 'Travel Tech',
    rating: 4.8,
    popular: false,
    targetUsers: 'Travel Agencies, Tour Operators, Visa Consultants, Hajj Agencies',
    modules: ['Ticketing Ledger', 'Visa Tracking', 'Package Builder', 'Passenger Passport Vault', 'Vendor Accounts', 'Invoicing']
  },
  {
    id: 'ecommerce-multivendor',
    name: 'E-Commerce & Multi-Vendor Marketplace',
    category: 'Retail & POS',
    shortDescription: 'Modern online store with mobile app, bKash/Nagad/Cards payment gateway, inventory, and vendor payout system.',
    fullDescription: 'Launch your single-store or multi-vendor marketplace like Daraz. Features responsive React frontend, admin control center, merchant dashboards, automated shipping fee calculation, and promo code discounts.',
    features: ['bKash, Nagad & Card Gateways', 'Multi-Vendor Commission Payouts', 'Order Dispatch & Courier Sync', 'Mobile App API Ready'],
    icon: 'bi-cart4',
    badge: 'High Conversion',
    rating: 4.9,
    popular: true,
    targetUsers: 'Online Brands, Wholesale Marketplaces, Niche E-Commerce Retailers',
    modules: ['Storefront UI', 'Vendor Portal', 'Order Management', 'Payment Gateways', 'Coupons & Promos', 'Customer Mobile App']
  },
  {
    id: 'gym-fitness',
    name: 'Gym & Fitness Club Management',
    category: 'Services & Logistics',
    shortDescription: 'Member subscriptions, biometric turnstile check-in, personal trainer schedule, locker allocation, and SMS reminders.',
    fullDescription: 'Manage fitness centers effortlessly. Monitor active/expired memberships, turnstile gate integration, workout plan assignments, diet tracking, locker rentals, and automated dues SMS notifications.',
    features: ['Biometric Gate Access Control', 'Membership Expiry SMS Alerts', 'Personal Trainer Rosters', 'Supplement Sales Counter'],
    icon: 'bi-activity',
    badge: 'Fitness Tech',
    rating: 4.7,
    popular: false,
    targetUsers: 'Gyms, Fitness Clubs, Martial Arts Academies, Sports Complexes',
    modules: ['Member Registry', 'Turnstile Access', 'Package Renewal', 'Locker & Diet Tracker', 'Supplement POS', 'Accounts']
  },
  {
    id: 'apartment-society',
    name: 'Apartment & Housing Society Management',
    category: 'Real Estate & Infrastructure',
    shortDescription: 'Monthly maintenance bill collection, visitor logging, security guard app, flat owner dashboard, and expense accounts.',
    fullDescription: 'Digitalize residential building management. Generate monthly service charges, utility bill ledgers, online payment collection via bKash, digital visitor gate passes, and committee financial reports.',
    features: ['Automated Monthly Bill Generator', 'bKash/Nagad Online Bill Pay', 'Visitor & Security Gate App', 'Building Committee Audit'],
    icon: 'bi-building-gear',
    badge: 'Smart Housing',
    rating: 4.8,
    popular: false,
    targetUsers: 'Apartment Associations, Housing Societies, Commercial Buildings',
    modules: ['Flat Owner Registry', 'Maintenance Bill Engine', 'Visitor Gate Log', 'Building Expense Ledger', 'Notice Board App']
  },
  {
    id: 'lpg-gas-dist',
    name: 'LPG Gas & Cylinder Distribution Software',
    category: 'Services & Logistics',
    shortDescription: 'Cylinder deposit tracking, dealer inventory, empty vs full cylinder stock, and driver delivery route ledger.',
    fullDescription: 'Specialized distribution software for LPG gas companies and dealers. Tracks empty cylinder returns, full cylinder stock, security deposit ledgers, dealer credit limits, and vehicle trip expenses.',
    features: ['Full vs Empty Cylinder Balance', 'Dealer Credit Limit Management', 'Security Deposit Ledger', 'Delivery Vehicle Trip Audit'],
    icon: 'bi-fire',
    badge: 'Distribution',
    rating: 4.8,
    popular: false,
    targetUsers: 'LPG Gas Dealers, Beverage Distributors, Bottled Water Companies',
    modules: ['Cylinder Inventory', 'Dealer Ledger', 'Empty Return Tracker', 'Vehicle Route Trip', 'Deposit Ledger', 'Billing']
  },
  {
    id: 'law-firm-mgmt',
    name: 'Law Firm & Legal Case Management',
    category: 'Services & Logistics',
    shortDescription: 'Legal case diary, next hearing date SMS alerts, client billing, advocate assignment, and document archiving.',
    fullDescription: 'Organize legal practices efficiently. Search cause lists, track upcoming court hearing dates, archive legal briefs & evidence securely, manage advocate team schedules, and log client legal fees.',
    features: ['Court Next Hearing Alerts', 'Digital Case Document Vault', 'Client Legal Fee Ledger', 'Advocate Schedule Calendar'],
    icon: 'bi-briefcase',
    badge: 'Legal Tech',
    rating: 4.7,
    popular: false,
    targetUsers: 'Law Firms, Corporate Legal Departments, Independent Advocates',
    modules: ['Case Diary', 'Hearing Date Alerts', 'Document Vault', 'Client Billing', 'Advocate Roster', 'Archiving']
  },
  {
    id: 'diagnostic-lab',
    name: 'Diagnostic & Laboratory Information System',
    category: 'Education & Health',
    shortDescription: 'Pathology analyzer machine sync, automated report generator, barcode sample tracking, and doctor referral commission.',
    fullDescription: 'High-precision diagnostic lab software. Connects with lab auto-analyzers for test data import, generates barcode tube stickers, prints branded lab reports, and tracks doctor referral fees.',
    features: ['Auto-Analyzer Machine Data Sync', 'Barcode Sample Tube Tracking', 'Doctor Referral Commission Ledger', 'Online Patient Report Download'],
    icon: 'bi-eyedropper',
    badge: 'Lab Certified',
    rating: 4.9,
    popular: false,
    targetUsers: 'Diagnostic Centers, Pathology Labs, Blood Banks',
    modules: ['Sample Barcoding', 'Machine Interfacing', 'Test Report Generator', 'Doctor Commission', 'Patient Portal', 'Billing']
  },
  {
    id: 'manufacturing-factory',
    name: 'Manufacturing & Factory Management',
    category: 'Enterprise & ERP',
    shortDescription: 'Raw material Bill of Materials (BOM), work orders, scrap tracking, production costing, and shop floor audit.',
    fullDescription: 'Control factory production lines. Define multi-level Bill of Materials (BOM), create work orders, track raw material batch consumption, monitor machine downtime, and analyze unit manufacturing cost.',
    features: ['Multi-Level Bill of Materials (BOM)', 'Work Order & Batch Tracking', 'Raw Material Inventory Deductions', 'Unit Manufacturing Cost Audit'],
    icon: 'bi-gear-wide-connected',
    badge: 'Industrial',
    rating: 4.9,
    popular: false,
    targetUsers: 'Manufacturing Plants, Plastics, Chemical, Food Processing, Steel Mills',
    modules: ['BOM Manager', 'Work Order Control', 'Raw Material Inventory', 'Shop Floor Audit', 'Wastage Tracker', 'Costing']
  },
  {
    id: 'freight-forwarding',
    name: 'Freight Forwarding & Customs Clearing',
    category: 'Services & Logistics',
    shortDescription: 'Shipping manifest, H.S. Code lookup, CNF billing, container tracking, port charges, and customs documentation.',
    fullDescription: 'Customized software for freight forwarders and Clearing & Forwarding (C&F) agents. Handles Bill of Lading (B/L), customs Assessment Notices, port duty bills, container movement, and consignment ledgers.',
    features: ['Bill of Lading (B/L) Generator', 'Port & Customs Expense Ledger', 'Container Status Tracking', 'H.S. Code Duty Duty Calculator'],
    icon: 'bi-box-seam',
    badge: 'Logistics',
    rating: 4.8,
    popular: false,
    targetUsers: 'C&F Agencies, Freight Forwarders, Shipping Lines, Customs Brokers',
    modules: ['B/L Management', 'Consignment Ledger', 'Customs Duty Engine', 'Container Tracker', 'Invoicing', 'Accounts']
  }
];

const TECH_STACK = [
  { name: 'React.js', category: 'Frontend', iconClass: 'devicon-react-original colored', description: 'Component-based UI library for ultra-fast web interfaces.' },
  { name: 'Next.js', category: 'Frontend', iconClass: 'devicon-nextjs-original-wordmark colored', description: 'Server-side rendering & static site generation framework.' },
  { name: 'Vue.js', category: 'Frontend', iconClass: 'devicon-vuejs-plain colored', description: 'Progressive JavaScript framework for interactive web views.' },
  { name: 'HTML5', category: 'Frontend', iconClass: 'devicon-html5-plain colored', description: 'Modern semantic web structure and markup standard.' },
  { name: 'CSS3 / SCSS', category: 'Frontend', iconClass: 'devicon-sass-original colored', description: 'Advanced responsive styling, animations, and SASS preprocessor.' },
  { name: 'Tailwind CSS', category: 'Frontend', iconClass: 'devicon-tailwindcss-sharp colored', description: 'Utility-first CSS framework for rapid modern UI development.' },
  { name: 'Bootstrap', category: 'Frontend', iconClass: 'devicon-bootstrap-plain colored', description: 'Responsive mobile-first component grid system.' },

  { name: 'Node.js', category: 'Backend', iconClass: 'devicon-nodejs-plain colored', description: 'Scalable event-driven JavaScript server runtime.' },
  { name: 'Express.js', category: 'Backend', iconClass: 'devicon-express-original colored', description: 'Minimalist and fast web API backend framework for Node.' },
  { name: 'Laravel (PHP)', category: 'Backend', iconClass: 'devicon-laravel-original colored', description: 'Robust, elegant PHP MVC framework for enterprise web apps.' },
  { name: 'CodeIgniter (PHP)', category: 'Backend', iconClass: 'devicon-codeigniter-plain colored', description: 'Lightweight and high-speed PHP framework for quick applications.' },

  { name: 'Flutter', category: 'Mobile', iconClass: 'devicon-flutter-plain colored', description: 'Google cross-platform SDK for iOS and Android apps.' },

  { name: 'MySQL', category: 'Databases', iconClass: 'devicon-mysql-plain colored', description: 'High-performance relational database management system.' },
  { name: 'Firebase', category: 'Databases', iconClass: 'devicon-firebase-plain colored', description: 'Google cloud real-time NoSQL database & authentication platform.' },

  { name: 'TypeScript', category: 'Languages & Tools', iconClass: 'devicon-typescript-plain colored', description: 'Strongly typed JavaScript superset for scalable codebase.' },
  { name: 'JavaScript (ES6+)', category: 'Languages & Tools', iconClass: 'devicon-javascript-plain colored', description: 'Modern dynamic web programming language.' },
  { name: 'REST API', category: 'Languages & Tools', iconClass: 'bi bi-arrow-repeat text-primary fs-2', description: 'Standardized JSON web API communication protocol.' },
  { name: 'AWS', category: 'Languages & Tools', iconClass: 'devicon-amazonwebservices-plain-wordmark colored', description: 'Amazon Cloud Infrastructure, EC2, S3 & RDS deployment.' },
  { name: 'Git & GitHub', category: 'Languages & Tools', iconClass: 'devicon-github-original colored', description: 'Version control system and code collaboration platform.' },
  { name: 'GitLab', category: 'Languages & Tools', iconClass: 'devicon-gitlab-plain colored', description: 'DevOps lifecycle and CI/CD automated deployment pipelines.' },
  { name: 'Vercel', category: 'Languages & Tools', iconClass: 'devicon-vercel-original colored', description: 'Instant serverless web hosting & edge deployment.' },
  { name: 'Netlify', category: 'Languages & Tools', iconClass: 'devicon-netlify-plain colored', description: 'Modern static web publishing & continuous integration.' },
  { name: 'Nginx', category: 'Languages & Tools', iconClass: 'devicon-nginx-original colored', description: 'High-performance web server, reverse proxy & load balancer.' },
  { name: 'Apache', category: 'Languages & Tools', iconClass: 'devicon-apache-plain colored', description: 'Reliable cross-platform HTTP web server.' },
];

const COMPANY_STATS = [
  {
    id: 'projects',
    label: 'Projects Completed',
    value: '1200+',
    icon: 'bi-check-circle-fill',
    description: 'Custom software, web applications, and mobile apps successfully delivered.'
  },
  {
    id: 'clients',
    label: 'Satisfied Clients',
    value: '1000+',
    icon: 'bi-emoji-smile-fill',
    description: 'Businesses, educational institutes, and healthcare organizations served.'
  },
  {
    id: 'employees',
    label: 'Expert Team Members',
    value: '36+',
    icon: 'bi-people-fill',
    description: 'Skilled software engineers, UI/UX designers, and network specialists.'
  },
  {
    id: 'support',
    label: 'Technical Support',
    value: '24/7',
    icon: 'bi-clock-history',
    description: 'Round-the-clock server monitoring, technical troubleshooting, and maintenance.'
  },
  {
    id: 'success-rate',
    label: 'Success Rate',
    value: '95%',
    icon: 'bi-award-fill',
    description: 'On-time delivery, high client satisfaction, and long-term retainer partnerships.'
  },
];

const DOMAIN_PRICING = [
  { tld: '.com', priceUsd: '$12.99', priceBdt: '\u09f31,400', period: '/year', tag: 'Most Popular', popular: true },
  { tld: '.com.bd', priceUsd: '$22.00', priceBdt: '\u09f32,500', period: '/year', tag: 'Official BD', popular: true },
  { tld: '.net', priceUsd: '$14.99', priceBdt: '\u09f31,650', period: '/year', tag: 'Tech Standard', popular: false },
  { tld: '.org', priceUsd: '$13.99', priceBdt: '\u09f31,550', period: '/year', tag: 'Non-Profit', popular: false },
  { tld: '.bd', priceUsd: '$25.00', priceBdt: '\u09f33,000', period: '/year', tag: 'National TLD', popular: false },
  { tld: '.info', priceUsd: '$9.99', priceBdt: '\u09f31,100', period: '/year', tag: 'Information', popular: false },
  { tld: '.xyz', priceUsd: '$3.99', priceBdt: '\u09f3450', period: '/year', tag: 'Budget', popular: false },
];

const CLIENT_LOGOS = [
  { name: 'Standard Group BD', sector: 'Textile & Garments' },
  { name: 'Pran-RFL Partner Network', sector: 'FMCG & Retail' },
  { name: 'Popular Diagnostic Center Partner', sector: 'Healthcare' },
  { name: 'Uttara Motors Partner', sector: 'Automotive' },
  { name: 'Dhaka Ideal Academy', sector: 'Education' },
  { name: 'Beximco Partner Network', sector: 'Enterprise' },
  { name: 'Square Hospitals Network', sector: 'Healthcare' },
  { name: 'ACI Logistics Partner', sector: 'Logistics' },
];

const TESTIMONIALS = [
  {
    id: '1',
    name: 'Engr. Rafiqul Islam',
    role: 'Managing Director',
    company: 'Apex Garments & Textile Ltd.',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200',
    text: 'STITBD developed our enterprise Garments ERP and HR Payroll system. The biometric attendance sync and automated export documentation saved us hundreds of manual hours every month.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Dr. Sharmin Akter',
    role: 'Chief Medical Officer',
    company: 'Care Diagnostic & Hospital',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    text: 'The Hospital & Diagnostic Management software from STITBD is remarkably smooth. Pathologists can sync machine data directly, and patients receive SMS download links for lab reports.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Mahmudul Hasan',
    role: 'Head of Operations',
    company: 'QuickCourier BD',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
    text: 'Our nationwide courier tracking system built by STITBD handles over 10,000 daily parcel bookings effortlessly. The merchant portal and rider app are fast and foolproof.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Principal M. A. Karim',
    role: 'Founder & Principal',
    company: 'Green Valley International School',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    text: 'We have been using STITBD\u2019s School Management System since 2018. Online bKash fee collection and instant exam result publishing transformed our parent communication.',
    rating: 5,
  }
];
